name: Publish NPM Package

on:
  push:
    branches:
      - main  # Trigger on push to the main branch, adjust as needed

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:

      # - name: Git configuration
      #   run: |
      #     git config --global user.email "patrick.deklein@cito.nl"
      #     git config --global user.name "patrickdeklein"

      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Dependencies
        run: npm install

      - name: Publish to NPM
        run: npm version prepatch

        # Push repository changes
      # - name: Push changes to repository
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: git push origin && git push --tags

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --tag next
        

      - name: Verify Package
        run: npm info @citolab/qti-components
